package com.helder.springbootlizards.model;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "${lizards.table.name}")
public class Lizard {
  private String id;
  private String species;
  private String commonName;
  private String picture;

  public Lizard() { }

  public Lizard(String species, String commonName, String picture) {
    this.species = species;
    this.commonName = commonName;
    this.picture = picture;
  }

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  public String getId() {
    return id;
  }

  @DynamoDBAttribute
  public String getSpecies() {
    return species;
  }

  @DynamoDBAttribute
  public String getCommonName() {
    return commonName;
  }

  @DynamoDBAttribute
  public String getPicture() {
    return picture;
  }

}
